apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: metric-500-error-ingress
spec:
  provider:
    type: prometheus
    address: http://po-prometheus.monitoring:9090
  query: |
     sum(
        rate(
        http_requests_total{
          job="{{`{{ target }}`}}", 
          status=~"5.*", 
          path!~"/manage/*"}
          ["{{`{{ interval }}`}}"])) OR on() vector(0)
      /
      sum(
        rate(
          http_requests_total{
            job="{{`{{ target }}`}}", 
            path!~"/manage/*"}
            ["{{`{{ interval }}`}}"]))OR on() vector(0)
        * 100
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: metric-500-error-node
spec:
  provider:
    type: prometheus
    address: http://po-prometheus.monitoring:9090
  query: |
      sum(
        rate(
        http_requests_total{
          job="{{`{{ target }}`}}", 
          status=~"5.*", 
          path!~"/manage/*"}
          ["{{`{{ interval }}`}}"])) OR on() vector(0)
      /
      sum(
        rate(
          http_requests_total{
            job="{{`{{ target }}`}}", 
            path!~"/manage/*"}
            ["{{`{{ interval }}`}}"]))OR on() vector(0)
      * 100
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: metric-500-error-java
spec:
  provider:
    type: prometheus
    address: http://po-prometheus.monitoring:9090
  query: |
      sum(
        rate(
          http_server_requests_seconds_count{
            job="{{`{{ target }}`}}", 
            status=~"5.*"}
            ["{{`{{ interval }}`}}"])
            OR vector(0)) 
      /
      sum(
        rate(
          http_server_requests_seconds_count{
            job="{{`{{ target }}`}}",
            status=~"2.*"}
            ["{{`{{ interval }}`}}"]
            )OR vector(0)) 
            * 100